backend:
  name: github
  branch: main
  repo: whitespace-se/docs.municipio.se
  base_url: https://oauth.dev.w8e.se
  logo_url: https://whitespace.se/favicon.svg
  site_url: https://docs.municipio.se/
  display_url: https://docs.municipio.se/
  slug:
    encoding: "ascii"
    clean_accents: true
    sanitize_replacement: "_"

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: docs
  label: Docs
  folder: docs
  nested:
    depth: 500
    summary: '{{title}}'
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  fields:
    - { name: title, label: Title, widget: string }
    - { name: slug, label: Slug, widget: string }
    - { name: sidebar_position, label: Sidebar position, widget: number }
    - { name: body, label: Body, widget: markdown }
