const sidebars = {
  defaultSidebar: [],
  editor: [
    {
      type: "category",
      label: "Redaktör",
      items: [{ type: "autogenerated", dirName: "editor" }],
    },
  ],
  admin: [
    {
      type: "category",
      label: "Administratör",
      items: [{ type: "autogenerated", dirName: "admin" }],
    },
  ],
  developer: [
    {
      type: "category",
      label: "Utvecklare",
      items: [{ type: "autogenerated", dirName: "developer" }],
    },
  ],
};

module.exports = sidebars;
